In [2]:
import pandas as pd

<h3> Task #5 Which actor/actress shows up most frequently in the netflix database

In [17]:
df=pd.read_csv('~/Documents/netflix_titles.csv')
casts=df['cast'].reset_index()
casts=casts.cast.str.lower().str.split(',').explode().reset_index()

casts=casts.groupby('cast').agg({'cast':'count'})
casts.rename(columns={'cast':'count'},inplace=True)
casts.reset_index().sort_values('count',ascending=False).head(50)

                      cast  count
2610           anupam kher     39
26954         rupa bhimani     31
30311     takahiro sakurai     30
15560        julie tejwani     28
23639              om puri     27
25421          rajesh kava     26
38436       shah rukh khan     26
23969         paresh rawal     25
33383            yuki kaji     25
1904         andrea libman     25
4184           boman irani     25
32305         vincent tong     24
34027         akshay kumar     23
14173       jigna bhardwaj     23
15674       junichi suwabe     21
10149      fred tatasciore     21
22518     naseeruddin shah     20
16041       kareena kapoor     20
34158     amitabh bachchan     20
14603          john cleese     20
35073   david attenborough     20
33938         adam sandler     20
625              ai kayano     19
6731           daisuke ono     18
11147       gulshan grover     18
33048       yashpal sharma     18
38997         vatsal dubey     18
988     alessandro juliani     17
9356       erin fitzgerald     17
10016     fortune feimster     17
15925        kana hanazawa     17
3063                asrani     17
25428        rajesh sharma     17
31355      tomokazu sugita     16
16070        kari wahlgren     16
7928         diana kaarina     16
32222           vijay raaz     16
1665           amrish puri     16
37608         nicolas cage     16
22008        molly shannon     16
34020           ajay devgn     16
4405        brian drummond     16
1204         alfred molina     16
21318        michael palin     16
19582          manoj joshi     16
30500          tara strong     16
20790         maya rudolph     16
31096          tinnu anand     16
33364      yuichi nakamura     16
11610         hassan hosny     16